export class Sale{
    id?:string;
    orderId?:string;
    orderDate?:string;
    shipDate?:string;
    shipMode?:string;
    customerId?:string;
    customerName?:string;
    segment?:string;
    country?:string;
    city?:string;
    state?:string;
    postalCode?:string;
    region?:string;
    productId?:string;
    category?:string;
    subCategory?:string;
    productName?:string;
    sales?:number;
    quantity?:number;
    discount?:number;
    profit?:number;
    constructor(id?:string,sales?:number,quantity?:number,discount?:number,profit?:number,orderId?:string,orderDate?:string,
        shipDate?:string,shipMode?:string,customerId?:string,customerName?:string,segment?:string,country?:string,
        city?:string,state?:string,postalCode?:string,region?:string,productId?:string,category?:string,
        subCategory?:string,productName?:string){
            this.id=id;
            this.orderId=orderId;
            this.orderDate=orderDate;
            this.shipDate=shipDate;
            this.shipMode=shipMode;
            this.customerId=customerId;
            this.customerName=customerName;
            this.segment=segment;
            this.country=country;
            this.city=city;
            this.state=state;
            this.postalCode=postalCode;
            this.region=region;
            this.productId=productId;
            this.category=category;
            this.subCategory=subCategory;
            this.productName=productName;
            this.sales=sales;
            this.quantity=quantity;
            this.discount=discount;
            this.profit=profit;
        }
}